version: "3.8"
services:
  api:
    image: hoge-api
    container_name: hoge-api
    build:
      context: ./api
      dockerfile: ./../docker/dockerfile/Dockerfile-local
    environment:
      - GO_ENV=local
      - GIN_MODE=debug
    volumes:
      - ./api:/app/server
    ports:
      - "8080:8080"
  mysql:
    build: ./docker/db
    platform: linux/x86_64
    container_name: "hoge-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hogehoge
      MYSQL_USER: hoge
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
      LC_ALL: "ja_JP.UTF-8"
    ports:
      - "9906:3306"
    volumes:
      - "./docker/db/data:/var/lib/mysql"
      - "./docker/db/conf:/etc/mysql/conf.d"
      - "./docker/db/init:/docker-entrypoint-initdb.d"
      - "./docker/db/logs:/var/log/mysql"
