FROM golang:1.19-alpine

ENV GO111MODULE=on
ENV TZ Asia/Tokyo

RUN mkdir -p /app/server
WORKDIR /app/server

RUN go install github.com/cosmtrek/air@latest

RUN pwd
COPY go.mod go.sum ./
RUN go mod download

COPY ./ ./

CMD ["air", "-c", ".air.toml"]

# RUN go build -o /tmp/main

# CMD [ "/tmp/main" ]

# CMD ["go","run","main.go"]